development:
  adapter: postgresql
  encoding: unicode
  database: appname-dev
  pool: 5
  host: localhost
  username: action
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: appname-test
  pool: 5
  host: localhost
  username: action
  password:

production:
	url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: unicode
  database: appname-prod
  pool: 5
  host: localhost
  username: action
  password: